version: '3'

services:
  client:
    container_name: client-container
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./client/:/usr/src/app
    command: yarn start
    tty: true
    depends_on:
      - api
  api:
    container_name: api-container
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    container_name: db-container
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - 'db-data:/var/lib/mysql'
      - './docker/db/config/my.cnf:/etc/mysql/conf.d/mysql.cnf'
      - './docker/db/initial_db:/docker-entrypoint-initdb.d'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'TZ="Asia/Tokyo"'

volumes:
  db-data:
